; PlatformIO Project Configuration File
;
; Railway Signaling System v2.1
; For Arduino Mega 2560

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter =
    +<*>
    -<sim/>
monitor_speed = 9600
monitor_eol = LF
monitor_echo = yes
build_flags = 
    -Wall
    -Wextra
upload_speed = 115200

upload_port = COM3

[env:megaatmega2560_sim]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter =
    +<*>
    -<main.cpp>
    -<signal_control.cpp>
monitor_speed = 9600
monitor_eol = LF
monitor_echo = yes
build_flags =
    -Wall
    -Wextra